version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - pip install --upgrade pip
      - pip install pipenv --user
      - pipenv install
      - pipenv run sam validate
      - pipenv run sam deploy --no-fail-on-empty-changeset