Parameters:
  SecretName:
    Type: String
    Default: GitHubOAuthToken

Resources:
  GitHubOAuth:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      GenerateSecretString: {}
      Name: !Ref SecretName

Outputs:
  LogicalID:
    Description: Name of the Secret where the GitHub OAuth token is stored
    Value: !Ref SecretName
    Export: 
      Name: GitHubOAuthSecretName
