AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  SimpleStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: ./statemachines/definition.asl.json
      DefinitionSubstitutions:
        GetAccountListArn: !GetAtt GetAccountList.Arn
        DeployStackArn: !GetAtt DeployStack.Arn
      Policies:
        - CloudWatchPutMetricPolicy: {}
        - LambdaInvokePolicy:
            FunctionName: !Ref GetAccountList
        - LambdaInvokePolicy:
            FunctionName: !Ref DeployStack

  GetAccountList:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/get_account_list/
      Handler: function.handler
      Runtime: python3.7

  DeployStack:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/deploy_stack/
      Handler: function.handler
      Runtime: python3.7

Outputs:
  StateMachineArn:
    Value: !Ref SimpleStateMachine
    Export: 
      Name: StateMachineArn
