AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  SimpleStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Definition:
        StartAt: GetTemplates
        States:
          GetTemplates:
            Resource: !GetAtt GetTemplatesFunction.Arn
            Type: Task
            End: true
      Policies:
        - CloudWatchPutMetricPolicy: {}
        - LambdaInvokePolicy:
            FunctionName: !Ref GetTemplatesFunction

  GetTemplatesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/get_templates/
      Handler: app.handler
      Runtime: python3.7

Outputs:
  StateMachineArn:
    Value: !Ref SimpleStateMachine
    Export: 
      Name: StateMachineArn
