AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  OrgId:
    Type: String
    Default: o-lhtws2v9du

Resources:
  SimpleStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: ./statemachines/definition.asl.json
      DefinitionSubstitutions:
        GetAccountListArn: !GetAtt GetAccountList.Arn
        DeployStackArn: !GetAtt DeployStack.Arn
      Policies:
        - CloudWatchPutMetricPolicy: {}
        - LambdaInvokePolicy:
            FunctionName: !Ref GetAccountList
        - LambdaInvokePolicy:
            FunctionName: !Ref DeployStack

  GetAccountList:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/get_account_list/
      Handler: function.handler
      Runtime: python3.7

  DeployStack:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/deploy_stack/
      Environment:
        Variables:
          ROLE_NAME: CrossAccountDeploy
          STACK_NAME: Bucket
          BUCKET_NAME: !Ref TemplateStore
          BUCKET_PREFIX: template.yaml
      Handler: function.handler
      Runtime: python3.7

  TemplateStore:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      AccessControl: Private

  TemplateStorePolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref TemplateStore
      PolicyDocument:
        Statement:
          - Action: 's3:GetObject'
            Effect: Allow
            Principal: "*"
            Resource: !Join
              - ""
              - - "arn:aws:s3:::"
                - !Ref TemplateStore
                - "/*"
            Condition:
              StringEquals:
                "aws:PrincipalOrgId":
                  - !Ref OrgId

Outputs:
  StateMachineArn:
    Value: !Ref SimpleStateMachine
    Export: 
      Name: StateMachineArn

  TemplateStoreName:
    Value: !Ref TemplateStore
    Export:
      Name: TemplateStoreName
